spring:
   application:
    name: eureka-service
server:
   port: 8762
  
eureka:
   instance:
    hostname: server2
   client:    
    service-url:
      default-zone: http://server1:8761/eureka/,http://server3:8763/eureka/ 