#spring:
#   application:
#    name: eureka-server
#server:
#   port: 8761
#  
#eureka:
#   instance:
#    hostname: server1
#   client:    
#    service-url:
#      defaultZone: http://server2:8762/eureka/,http://server3:8763/eureka/
     
    
#spring:
#   application:
#    name: eureka-service
#server:
#   port: 8762
#  
#eureka:
#   instance:
#    hostname: server2
#   client:    
#    service-url:
#      defaultZone: http://server1:8761/eureka/,http://server3:8763/eureka/ 

      
spring:
  application:
    name: eureka-service
server:
  port: 8763
  
eureka:
  instance:
    hostname: server3
  client:
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/