spring:
  boot:
    admin:          
#      discovery:
#        ignored-services: consul
      ui:
        # 修改网页显示的tab标题
        title: "应用监控管理"
        # 修改网页的brand的图标和标题
        #brand: "<img src='assets/img/icon-spring-boot-admin.svg'><span>应用监控管理</span>"
      notify:
        mail:
          ignore-changes: 
          - ""         
          from: 854128573@qq.com
          #to: xuliqunpersonal@hotmail.com
          to: 854128573@qq.com         
  security:
    user:
      name: admin
      password: admin
  