#这个配置文件的配置没看到起作用
#spring:  
#  cloud:      
#    consul:    
#      discovery:                        #字符串不能为空,首字符必须为字母,尾字符必须为字母或数字,所有非字母数字的字符统一转换成'-'连接符,同时多个连续连接符转换成一个'-'. 
#        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.cloud.client.hostname}:${random.int} #实例ID
        #health-check-path: /actuator/health #健康检查
        #health-check-interval: 10s  