eureka:
  instance:
    prefer-ip-address: true    
    #non-secure-port: ${server.port:8888}
    instance-id: ${spring.cloud.client.ip-address}:${spring.cloud.client.hostname}:${spring.application.name}:${random.int}:@project.version@
    appname: ${spring.application.name}   
  client:
    service-url:
      default-zone: http://server1:8761/eureka/,http://server2:8762/eureka/,http://server3:8763/eureka/
      #http://${eureka.instance.hostname}:${eureka.port}/eureka/


#spring:
#  profiles:
#    active: csdn
#zuul:
#  routes:
#    consumer: /consumer/**
#    service: /service/**
#    consumer-feign: /consumerfeign/**
#    auth-client: /authClient/**
#    auth-service: /authService/**
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 80000

# keycloak:
#   realm : springcloud-zuul
#   auth-server-url : http://127.0.0.1:8080/auth
#   ssl-required : external
#   resource : springcloud-zuul
#   credentials.secret : 11111111-1111-1111-1111-111111111111
#   use-resource-role-mappings : true
#   enable-basic-auth: true
#   securityConstraints:
#     - authRoles: user
#       securityCollections:
#          - patterns:  /provider/user/info
#     - authRoles: users
#       securityCollections:
#          - patterns:  /consumer/user/list
#     - authRoles: test
#       securityCollections:
#          - patterns:  /provider/user/list

# hystrix.command.default.execution.timeout.enabled: false

