eureka:
  instance:
    prefer-ip-address: true    
    #non-secure-port: ${server.port:8888}
    instance-id: ${spring.cloud.client.ip-address}:${spring.cloud.client.hostname}:${spring.application.name}:${random.int}:@project.version@
    appname: ${spring.application.name}   
  client:
    service-url:
      default-zone: http://server1:8761/eureka/,http://server2:8762/eureka/,http://server3:8763/eureka/

logging:
  level:
    com.yasaka.stock.feign.MFeignClient: debug
    org.springframework.security: DEBUG
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout:  30000
  ConnectTimeout:  15000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000
            
merryyou:
  security:
    code:
      image:
        width: 90
        height: 20
        length: 4
        expireIn: 30
        url: /code/*
    session:
      maximumSessions: 1
      maxSessionsPreventsLogin: false
#      sessionInvalidUrl : /merryyou-session-invalid.html
    loginType: JSON