eureka:
  instance:
    prefer-ip-address: true    
    #non-secure-port: ${server.port:8888}
    instance-id: ${spring.cloud.client.ip-address}:${spring.cloud.client.hostname}:${spring.application.name}:${server.port}:0.0.1-SNAPSHOT
    appname: ${spring.application.name}   
  client:
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/,http://server3:8763/eureka/

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/dev, classpath:/config/prod
#    bus:   #TODO
#      trace:
#        enabled: true
#  security:
#    basic:
#      enabled: true
#    user:
#      name: root
#      password: booszy  
  profiles:
    active: native #native/remote   #native表示本地方式 #这个不要随意改   
server:
  port: 8888 

# 允许/actuator/bus-refresh接口被外部调用
management:  
  endpoints:
    web:
      exposure:
        include: "*"  
