#配置查看factory-admin里application.yml的配置说明，目前在使用配置中心时，当前application.yml文件貌似读不到，不起作用
#spring:
#  cloud:   
#    consul:
#      host: 127.0.0.1 #consul节点IP
#      port: 8600       #consul节点端口
#      discovery:
#        #字符串不能为空,首字符必须为字母,尾字符必须为字母或数字,所有非字母数字的字符统一转换成'-'连接符,同时多个连续连接符转换成一个'-'. 
#        instance-id: ${spring.application.name}:@project.version@:${spring.cloud.client.ip-address}:${spring.cloud.client.hostname}:${random.int} #实例ID
        #health-check-path: /actuator/health #健康检查,默认配置，可以注释掉
        #health-check-interval: 10s #默认配置10s，可以注释掉
        #tags: management.context-path=/foo, health.path=/ping #, user.name=user, user.password=password

spring:
  influx:    url: http://localhost:8086/
    password: admin
    user: 123      
  mqtt:
    username: admin
    password: password
    host-url: tcp://127.0.0.1:1883
    client-id: mqttId
    default-topic: topic
  cloud:    stream:
      rabbit:        bindings:          input_channel:
            consumer:
              durable-subscription: true
              requeue-rejected: false
              max-concurrency: 5           
              acknowledge-mode: MANUAL
              recovery-interval: 3000
      bindings:
        output_channel:
          destination: exchange-3  #exchange名称，交换模式默认是topic
          group: queue-3 #队列名称
        input_channel:
          destination: exchange-3
          group: queue-3
          #binder: rabbit_culster
          consumer:            concurrency: 1
      binders:        defaultRabbit:
          type: rabbit
          environment:            spring:
              rabbitmq:
                address: localhost:5672
                username: guest
                password: guest
                virtual-host: /    
        